# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36553957bb4e6b9f199f68ca1f982ed7a9b2dfe2345478dd48ee34caf4895a45d996639551697f10421d3365b4715b46f8be436a73b94e4c3deae27de5feec8e

test:
  secret_key_base: 69135dd92eea52aec3adafa4588014cb1e2b7cbabf6d00d345c44f7467b700331b0699a1daf83ada65e8becb39e6f732996f23d35517dc3d83f424614e1f39c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
